services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: ['5173:5173']
    volumes: ['./frontend:/app']
    restart: unless-stopped
    tty: true
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports: ['4000:4000']
    volumes: ['./api:/app']
    restart: unless-stopped
    tty: true

  # todo: add mongodb and redis services
