# Bug Report
name: Bug Report
description: Report a bug in the Chameleon Engineer Blog project.
title: '[BUG] '
labels: bug
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide a detailed description of the bug you encountered. Include steps to reproduce, expected behavior, and actual behavior.
  - type: input
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug.
  - type: input
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: input
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that might help in diagnosing the issue.
  - type: checkbox
    id: include-screenshots
    attributes:
      label: Include Screenshots
      description: Check this box if you have screenshots to help illustrate the bug.
      options:
        - label: Yes
          value: yes
          default: false
  - type: input
    id: screenshot-links
    attributes:
      label: Screenshot Links
      description: If you checked the box above, please provide links to the screenshots.
      placeholder: 'https://example.com/screenshot1.png, https://example.com/screenshot2.png'
      condition: include-screenshots == 'yes'
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment (e.g., browser version, operating system).
      placeholder: 'e.g., Chrome 90 on Windows 10'
  - type: input
    id: version
    attributes:
      label: Version
      description: Specify the version of the Chameleon Engineer Blog you are using.
      placeholder: 'e.g., 1.0.0'
  - type: input
    id: contact-info
    attributes:
      label: Contact Information
      description: Provide your contact information if you would like to be notified about the resolution of this bug.
      placeholder: 'e.g., yourname@example.com'
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: Any other comments or information you would like to add.
      placeholder: 'Optional comments or suggestions'
