name: Update Changelog (Development)

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
      - master
    paths:
      - 'package.json'

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update changelog with unreleased changes
        run: npm run changelog:update

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet CHANGELOG.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true' && github.event_name != 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: update changelog with unreleased changes'
          title: 'Update Changelog'
          body: |
            This PR updates the changelog with recent unreleased changes.

            Auto-generated by GitHub Actions.
          branch: update-changelog
          delete-branch: true

      - name: Commit changes (manual trigger)
        if: steps.changes.outputs.changed == 'true' && github.event_name == 'workflow_dispatch'
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update changelog with unreleased changes"
          git push
